# Generated by Django 4.0.5 on 2022-09-27 02:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hamburger', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BurgerKing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='メニュー名')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='値段')),
                ('ditail', models.TextField(blank=True, null=True, verbose_name='詳細')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='写真')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name_plural': 'BurgerKing',
            },
        ),
        migrations.CreateModel(
            name='Mos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='メニュー名')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='値段')),
                ('ditail', models.TextField(blank=True, null=True, verbose_name='詳細')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='写真')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name_plural': 'Mos',
            },
        ),
        migrations.CreateModel(
            name='Mac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='メニュー名')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='値段')),
                ('ditail', models.TextField(blank=True, null=True, verbose_name='詳細')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='写真')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name_plural': 'Diary',
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('burgerking', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hamburger.burgerking', verbose_name='バーガーキング')),
                ('mac', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hamburger.mac', verbose_name='マック')),
                ('mos', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hamburger.mos', verbose_name='モスバーガー')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name_plural': 'Favorite',
            },
        ),
    ]
