# Generated by Django 4.1.1 on 2022-09-28 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hamburger', '0002_burgerking_mos_mac_favorite'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mac',
            options={'verbose_name_plural': 'Mac'},
        ),
    ]
