# Generated by Django 4.0.5 on 2022-09-30 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hamburger', '0004_remove_favorite_user_alter_burgerking_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favoritemac',
            options={'verbose_name_plural': 'FavoriteMac'},
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
