# Generated by Django 4.0.5 on 2022-09-30 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hamburger', '0004_auto_20220929_1339'),
        ('hamburger', '0005_alter_favoritemac_options_delete_favorite'),
    ]

    operations = [
    ]
